# Восстановление параметров распределения для региональных данных

In [24]:
import os
import pandas as pd
from tqdm import tqdm
from reg_normalizer import RegionMatcher

## 1. Подготовка таблицы с данными

In [25]:
POVERTY_FILE = './data/poverty_v2.xlsx'
LINE_FILE = './data/poverty_line_v2.xlsx'
INCOME_FILE = './data/average_income_v2.xlsx'
BASKET_FILE = './data/regional_basket_v2.xls'

In [26]:
matcher = RegionMatcher()

### 1.1. Потребительская корзина

In [59]:
basket = pd.read_excel(BASKET_FILE, sheet_name='Данные', skiprows=3, dtype='string')

In [60]:
month_columns = ['январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь']
basket['average'] = basket[month_columns].astype(float).mean(axis=1)
basket['rate'] = basket['average'] / basket.loc[0, 'average']
basket['Unnamed: 0'] = basket['Unnamed: 0'].str.strip()
basket = basket.rename(columns={'Unnamed: 0': 'region'})
basket = basket[~basket['region'].isin(['Архангельская область', 'Тюменская область'])]

In [61]:
basket = matcher.attach_fields(basket, 'region', ['name_rus', 'oktmo'])

In [62]:
matcher.get_match().head(10)

,original,normalized,score,event,note
0,Кемеровская область - Кузбасс,Кемеровская область,90.75,match,
1,Чувашская Республика - Чувашия,Чувашская Республика,92.00,match,
2,Ханты-Мансийский автономный округ - Югра (Тюме...,Ханты-Мансийский автономный округ — Югра,96.50,match,
3,Российская Федерация без учета новых субъектов...,Российская Федерация,100.00,match,
4,Центральный федеральный округ,Центральный федеральный округ,100.00,match,
5,Белгородская область,Белгородская область,100.00,match,
6,Брянская область,Брянская область,100.00,match,
7,Владимирская область,Владимирская область,100.00,match,
8,Воронежская область,Воронежская область,100.00,match,
9,Ивановская область,Ивановская область,100.00,match,

### 1.2. Уровень бедности

In [63]:
poverty = pd.read_excel(POVERTY_FILE, sheet_name='по РФ и субъектам РФ 2018-2025', skiprows=2, dtype='string')

In [64]:
poverty = poverty[['Unnamed: 0', '2025']][poverty['2025'].notna()]
poverty =poverty.rename(columns={'Unnamed: 0': 'region', '2025': 'poverty'})
poverty['region'] = poverty['region'].str.replace('в том числе:', '', regex=False).str.replace('\n', '', regex=False).str.strip()
poverty = poverty[~poverty['region'].isin(['Архангельская область', 'Тюменская область'])]
poverty = matcher.attach_fields(poverty, 'region', ['name_rus', 'oktmo'])

In [65]:
matcher.get_match().head(10)

,original,normalized,score,event,note
0,Чукотский авт.округ,Чукотский автономный округ,84.25,match,
1,Тюменская область без авт. округов,Тюменская область (без автономных округов),88.75,match,
2,г. Москва,Москва,89.25,match,
3,Архангельская область без авт. округа,Архангельская область (без автономного округа),90.00,match,
4,г. Севастополь,Севастополь,93.75,match,
5,г. Санкт-Петербург,Санкт-Петербург,95.50,match,
6,Российская Федерация,Российская Федерация,100.00,match,
7,Белгородская область,Белгородская область,100.00,match,
8,Брянская область,Брянская область,100.00,match,
9,Владимирская область,Владимирская область,100.00,match,

### 1.3. Граница бедности

In [66]:
poverty_line = pd.read_excel(LINE_FILE, sheet_name='по субъектам РФ 2025', skiprows=3, dtype='string')

In [67]:
poverty_line = poverty_line[['Unnamed: 0', 'Unnamed: 1']][poverty_line['Unnamed: 1'].notna()]
poverty_line = poverty_line.rename(columns={'Unnamed: 0': 'region', 'Unnamed: 1': 'poverty_line'})
poverty_line['region'] = poverty_line['region'].str.replace('в том числе:', '', regex=False).str.replace('\n', '', regex=False).str.strip()
poverty_line = poverty_line[~poverty_line['region'].isin(['Архангельская область', 'Тюменская область'])]
poverty_line = matcher.attach_fields(poverty_line, 'region', ['name_rus', 'oktmo'])

In [68]:
matcher.get_match().head(10)

,original,normalized,score,event,note
0,Город Москва,Москва,82.25,match,
1,Тюменская область без авт. округов,Тюменская область (без автономных округов),88.75,match,
2,Город Севастополь,Севастополь,89.00,match,
3,Архангельская область без авт. округа,Архангельская область (без автономного округа),90.00,match,
4,Ханты-Мансийский авт. округ - Югра,Ханты-Мансийский автономный округ — Югра,91.00,match,
5,Город Санкт-Петербург,Санкт-Петербург,91.50,match,
6,Российская Федерация,Российская Федерация,100.00,match,
7,Белгородская область,Белгородская область,100.00,match,
8,Брянская область,Брянская область,100.00,match,
9,Владимирская область,Владимирская область,100.00,match,

### 1.4. Среднедушевой доход

In [69]:
income = pd.read_excel(INCOME_FILE, sheet_name='СДД_субъекты', skiprows=2, dtype='string')

In [70]:
income = income[['Unnamed: 0', 'Unnamed: 75']][(income['Unnamed: 75'].notna()) & (income['Unnamed: 75'] != 'год 4)')]
income = income.rename(columns={'Unnamed: 0': 'region', 'Unnamed: 75': 'income'})
income['region'] = income['region'].str.replace('в том числе:', '', regex=False).str.replace('\n', '', regex=False).str.strip()
income = income[~income['region'].isin(['Архангельская область', 'Тюменская область'])]
income = matcher.attach_fields(income, 'region', ['name_rus', 'oktmo'])

In [71]:
matcher.get_match().head(10)

,original,normalized,score,event,note
0,г. Москва,Москва,89.25,match,
1,г. Севастополь,Севастополь,93.75,match,
2,г. Санкт-Петербург,Санкт-Петербург,95.50,match,
3,Тюменская область без автономных округов,Тюменская область (без автономных округов),97.25,match,
4,Архангельская область без автономного округа,Архангельская область (без автономного округа),98.25,match,
5,Российская Федерация,Российская Федерация,100.00,match,
6,Центральный федеральный округ,Центральный федеральный округ,100.00,match,
7,Белгородская область,Белгородская область,100.00,match,
8,Брянская область,Брянская область,100.00,match,
9,Владимирская область,Владимирская область,100.00,match,

### 1.5. Сводим данные вместе

In [72]:
merged = poverty.merge(poverty_line, on='name_rus', how='left').merge(income, on='name_rus', how='outer')
merged = merged[~merged['name_rus'].str.contains('федеральный округ', na=False)]
merged = merged[~merged['name_rus'].isin(['Архангельская область', 'Тюменская область'])]
merged = merged.merge(basket[['name_rus', 'average', 'rate']], on='name_rus', how='left')

In [73]:
del merged['region']
merged = merged.rename(columns={'name_rus': 'region', 'oktmo': 'region_code'})
merged['region_short_name'] = merged['region']

In [74]:
merged = merged[['region', 'poverty', 'poverty_line', 'income', 'average', 'rate', 'region_code', 'region_short_name']]
merged = merged.drop_duplicates()

In [75]:
merged.to_excel('./data/merged_v2.xlsx', index=False)

## 2. Расчет распределения доходов

In [76]:
from hack_params import HackParams

In [77]:
merged['income'] = merged['income'].astype(float)
merged['poverty'] = merged['poverty'].astype(float)
merged['poverty_line'] = merged['poverty_line'].astype(float)

In [78]:
poverty_steps_all = []

for idx, row in tqdm(merged.iterrows(), total=len(merged)):
    new_poverty = HackParams(average_income=row['income'], 
                             poverty_line=row['poverty_line'], 
                             poverty=row['poverty'])

    new_poverty.find_params()

    poverty_steps = pd.DataFrame({'sum': list(range(1000, 500001, 500))})
    poverty_steps['sum_corr'] = poverty_steps['sum']/row['rate']
    poverty_steps['share'] = poverty_steps['sum'].apply(new_poverty.count_poverty)
    poverty_steps['step_share'] = poverty_steps['share'] - poverty_steps['share'].shift(fill_value=0)

    last_share = poverty_steps['share'].iloc[-1]
    new_row = {
        'sum': 500050,
        'sum_corr': 500050/row['rate'],
        'share': 100,
        'step_share': 100 - last_share,
        'region': row['region'],
        'region_code': row['region_code'],
        'region_short_name': row['region_short_name'],
        'poverty': row['poverty'],
        'poverty_line': row['poverty_line'],
        'income': row['income']
    }
    poverty_steps = pd.concat([poverty_steps, pd.DataFrame([new_row])], ignore_index=True)

    poverty_steps['region'] = row['region']
    poverty_steps['region_code'] = row['region_code']
    poverty_steps['region_short_name'] = row['region_short_name']
    poverty_steps['poverty'] = row['poverty']
    poverty_steps['poverty_line'] = row['poverty_line']
    poverty_steps['income'] = row['income']
    poverty_steps['average'] = row['average']   
    poverty_steps['rate'] = row['rate']

    poverty_steps_all.append(poverty_steps)

poverty_steps_df = pd.concat(poverty_steps_all, ignore_index=True)

100%|██████████| 86/86 [00:27<00:00,  3.15it/s]

In [79]:
poverty_steps_df.to_excel('./data/poverty_steps_df_500_v20260506.xlsx', index=False)
poverty_steps_df.to_csv('./data/poverty_steps_df_500_v20260506.csv', index=False)

In [80]:
poverty_steps_df.head()

,sum,sum_corr,share,step_share,region,region_code,region_short_name,poverty,poverty_line,income,average,rate
0,1000,989.489116,0.00,0.00,Алтайский край,01000000,Алтайский край,10.9,15804.0,50506.0,25347.8525,1.010623
1,1500,1484.233674,0.00,0.00,Алтайский край,01000000,Алтайский край,10.9,15804.0,50506.0,25347.8525,1.010623
2,2000,1978.978232,0.00,0.00,Алтайский край,01000000,Алтайский край,10.9,15804.0,50506.0,25347.8525,1.010623
3,2500,2473.722790,0.01,0.01,Алтайский край,01000000,Алтайский край,10.9,15804.0,50506.0,25347.8525,1.010623
4,3000,2968.467348,0.02,0.01,Алтайский край,01000000,Алтайский край,10.9,15804.0,50506.0,25347.8525,1.010623